# Generated by Django 5.0.6 on 2024-06-05 06:43

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='Default Name', max_length=15, unique=True, verbose_name='Назва бізнесу')),
                ('address', models.CharField(default='УКРАЇНА, Київ', max_length=50, verbose_name='Адреса')),
                ('status', models.CharField(default='Закрито', max_length=10, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='business_photos/', verbose_name='Логотип бізнесу')),
                ('groups', models.ManyToManyField(blank=True, related_name='business_user_groups', to='auth.group', verbose_name='Групи')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='business_user_permissions', to='auth.permission', verbose_name='Дозволи користувача')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_photos/', verbose_name='Зоображення категорії')),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('descriprtion', models.TextField(max_length=200, verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos/', verbose_name='Зоображення товару')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.category')),
            ],
        ),
    ]
